# Generated by Django 5.1.3 on 2024-12-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('pharmacist', 'Pharmacist'), ('admin', 'Admin'), ('pharmacy_assistant', 'Pharmacy Assistant'), ('cashier', 'Cashier')], max_length=18),
        ),
    ]
