# Generated by Django 5.1.3 on 2024-12-05 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_current_stock'),
        ('transactions', '0003_saletransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetransaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product'),
        ),
    ]
