# Generated by Django 5.1.3 on 2024-12-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_purchasetransaction_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetransaction',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
