# Generated by Django 5.1.3 on 2024-12-06 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_saleitem_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitem',
            name='unit_price',
        ),
    ]
