# Generated by Django 5.1.3 on 2024-12-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_returntransaction_refund_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returntransaction',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=50),
        ),
    ]
