# Generated by Django 5.1.3 on 2024-12-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_returntransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returntransaction',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=50),
        ),
    ]
